### ISSUE TITLE
use in a web worker

### ISSUE THREAD

**Issue by lneir** [deregtd/NoSQLProvider#50]
hi... would like to use your library in a web worker... at least one issue i see is in https://github.com/Microsoft/NoSQLProvider/blob/master/src/IndexedDbProvider.ts#L38

this could be fixed by using 'self' if in context of web worker.

any other known issues that would prevent operation in web worker?

**Comment by deregtd** [comment]
The main problems you'll run into are that indexeddb isn't available inside a worker on safari, and websql (and localstorage) isn't available inside of a worker on any browser.  So, you'd be locked to indexeddb on non-safari browsers, and have no solution for safari (fall back to inmemoryprovider?..)

If you'd like to tweak things to have the indexeddb provider usable from inside a worker then I'd happily take the PR, though!

**Comment by lneir** [comment]
we should be good with those limitations.  i'm in experimental mode right now.  if things go well and we proceed with worker soln then i'll submit a PR.

**Comment by lneir** [comment]
@deregtd so our experiment worked out and we would like to submit PR to enable operation for indexDB in worker...proposed code change is as follows...

add method below to get window....

```
/**
 * Gets global window object - whether operating in worker or UI thread context.
 * Adapted from: https://stackoverflow.com/questions/7931182/reliably-detect-if-the-script-is-executing-in-a-web-worker
 */
getWindow() {
    if (typeof window === 'object' && window.document) {
        return window;
    } else if (self && self.document === undefined) {
        return self;
    }

    throw new Error('Undefined context');
}
```

then modify test for indexDb like this:
```
const global = this.getWindow();
this._dbFactory = global._indexedDB || global.indexedDB || global.mozIndexedDB || global.webkitIndexedDB || global.msIndexedDB;
```

does this seem reasonable?

**Comment by deregtd** [comment]
I would use another variable name than global, since on node, global means something else, but other than that, that seems fine to me if it helps on workers!  Open a PR!

**Comment by lneir** [comment]
@deregtd here is the PR: https://github.com/Microsoft/NoSQLProvider/pull/51
